language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
install:
  # Install unittest2 on Python 2.6
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  # Install coveralls (for coveralls.io integration)
  - pip install coveralls
  - pip install -r requirements.txt
script: python setup.py coverage
after_success: coveralls
